# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title C++ log-likelihood for fixed-dispersion beta interval regression
#' @description Total log-likelihood with a single dispersion parameter
#'   (last element of \code{param}); all four censoring types.
#' @param param  Numeric vector: \code{ncol(X)} coefficients, then phi (link scale).
#' @param X      Design matrix (n x p).
#' @param y_left,y_right Interval endpoints on (0, 1).
#' @param yt     Exact response on (0, 1) (used when \code{delta = 0}).
#' @param delta  Integer censoring indicators (0,1,2,3).
#' @param link_mu_code,link_phi_code Integer link codes (see \code{link_to_code}).
#' @param repar  Integer reparameterization type (0, 1, or 2).
#' @return Scalar log-likelihood value.
#' @keywords internal
.brs_loglik_fixed_cpp <- function(param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_loglik_fixed_cpp`, param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ log-likelihood for variable-dispersion beta interval regression
#' @description Total log-likelihood with observation-specific dispersion
#'   \code{Z gamma}; all four censoring types.
#' @param param Numeric vector: \code{ncol(X)} beta then \code{ncol(Z)} gamma.
#' @param X,Z   Design matrices of the mean (n x p) and dispersion (n x q).
#' @param y_left,y_right Interval endpoints on (0, 1).
#' @param yt     Exact response on (0, 1) (used when \code{delta = 0}).
#' @param delta  Integer censoring indicators (0,1,2,3).
#' @param link_mu_code,link_phi_code Integer link codes.
#' @param repar  Integer reparameterization type (0, 1, or 2).
#' @return Scalar log-likelihood value.
#' @keywords internal
.brs_loglik_variable_cpp <- function(param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_loglik_variable_cpp`, param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ gradient for the fixed-dispersion log-likelihood
#' @description Chain rule on the linear predictors:
#'   \code{crossprod(X, d_mu)} and \code{sum(d_phi)}, with per-observation
#'   derivatives by Richardson central differences (brs_deriv.h).
#' @inheritParams .brs_loglik_fixed_cpp
#' @return Numeric gradient vector of length \code{ncol(X) + 1}.
#' @keywords internal
.brs_grad_fixed_cpp <- function(param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_grad_fixed_cpp`, param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ gradient for the variable-dispersion log-likelihood
#' @description Chain rule on the linear predictors:
#'   \code{crossprod(X, d_mu)} and \code{crossprod(Z, d_phi)}
#'   (see \code{.brs_grad_fixed_cpp}).
#' @inheritParams .brs_loglik_variable_cpp
#' @return Numeric gradient vector of length \code{ncol(X) + ncol(Z)}.
#' @keywords internal
.brs_grad_variable_cpp <- function(param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_grad_variable_cpp`, param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ Hessian for the fixed-dispersion log-likelihood
#' @description Chain rule on the linear predictors:
#'   blocks \code{crossprod(X, w_mm * X)}, \code{crossprod(X, w_mp)} and
#'   \code{sum(w_pp)}, with per-observation
#'   second derivatives by Richardson central differences (17 evaluations).
#' @inheritParams .brs_loglik_fixed_cpp
#' @return Symmetric matrix of order \code{ncol(X) + 1} (log-likelihood scale).
#' @keywords internal
.brs_hessian_fixed_cpp <- function(param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_hessian_fixed_cpp`, param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ Hessian for the variable-dispersion log-likelihood
#' @description Chain rule on the linear predictors:
#'   blocks \code{crossprod(X, w_mm * X)}, \code{crossprod(X, w_mp * Z)} and
#'   \code{crossprod(Z, w_pp * Z)}.
#' @inheritParams .brs_loglik_variable_cpp
#' @return Symmetric matrix of order \code{ncol(X) + ncol(Z)} (log-likelihood scale).
#' @keywords internal
.brs_hessian_variable_cpp <- function(param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_hessian_variable_cpp`, param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

.brsmm_reset_cache <- function() {
    invisible(.Call(`_betaregscale_brsmm_reset_cache`))
}

.brsmm_loglik_eigen <- function(param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points) {
    .Call(`_betaregscale_brsmm_loglik_eigen`, param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points)
}

.brsmm_group_modes_eigen <- function(param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar) {
    .Call(`_betaregscale_brsmm_group_modes_eigen`, param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar)
}

.brsmm_mode_diag_cpp <- function(param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, warm) {
    .Call(`_betaregscale_brsmm_mode_diag_cpp`, param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, warm)
}

.brsmm_grad_cpp <- function(param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points) {
    .Call(`_betaregscale_brsmm_grad_cpp`, param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points)
}

.brsmm_hessian_cpp <- function(param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points) {
    .Call(`_betaregscale_brsmm_hessian_cpp`, param, X, Z, Xr, y_left, y_right, yt, delta, group, link_mu, link_phi, repar, method, n_points)
}

