# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title C++ log-likelihood for fixed-dispersion beta interval regression
#'   with mixed censoring
#' @description Computes the total log-likelihood for a beta regression model
#'   with interval-censored responses and a single (scalar) dispersion
#'   parameter, supporting all four censoring types (Lopes, 2024, Eq. 2.24).
#' @param param  Numeric vector: first \code{ncol(X)} elements are beta
#'   coefficients, the last element is the scalar dispersion parameter.
#' @param X      Design matrix (n x p).
#' @param y_left  Numeric vector of left interval endpoints on (0, 1).
#' @param y_right Numeric vector of right interval endpoints on (0, 1).
#' @param yt     Numeric vector of midpoint response on (0, 1).
#' @param delta  Integer vector of censoring indicators (0,1,2,3).
#' @param link_mu_code  Integer code for the mean link function.
#' @param link_phi_code Integer code for the dispersion link function.
#' @param repar  Integer reparameterization type (0, 1, or 2).
#' @return Scalar log-likelihood value.
#' @keywords internal
.betaregscale_loglik_fixed_cpp <- function(param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_loglik_fixed_cpp`, param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ log-likelihood for variable-dispersion beta interval regression
#'   with mixed censoring
#' @description Computes the total log-likelihood for a beta regression model
#'   with interval-censored responses and observation-specific dispersion,
#'   supporting all four censoring types (Lopes, 2024, Eq. 2.24).
#' @param param Numeric vector: first \code{ncol(X)} elements are beta
#'   coefficients, next \code{ncol(Z)} elements are gamma (phi) coefficients.
#' @param X      Design matrix for the mean submodel (n x p).
#' @param Z      Design matrix for the dispersion submodel (n x q).
#' @param y_left  Numeric vector of left interval endpoints on (0, 1).
#' @param y_right Numeric vector of right interval endpoints on (0, 1).
#' @param yt     Numeric vector of midpoint response on (0, 1).
#' @param delta  Integer vector of censoring indicators (0,1,2,3).
#' @param link_mu_code  Integer code for the mean link function.
#' @param link_phi_code Integer code for the dispersion link function.
#' @param repar  Integer reparameterization type (0, 1, or 2).
#' @return Scalar log-likelihood value.
#' @keywords internal
.betaregscale_loglik_variable_cpp <- function(param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_loglik_variable_cpp`, param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ gradient for fixed-dispersion log-likelihood
#' @description Returns the gradient vector of the log-likelihood with
#'   respect to all parameters (beta coefficients + scalar phi), using
#'   a central-difference numerical approximation (step = 1e-6).
#' @param param  Parameter vector (same layout as loglik function).
#' @param X      Design matrix (n x p).
#' @param y_left  Left endpoints.
#' @param y_right Right endpoints.
#' @param yt     Midpoint responses.
#' @param delta  Integer censoring indicators.
#' @param link_mu_code  Integer mean link code.
#' @param link_phi_code Integer dispersion link code.
#' @param repar  Integer reparameterization type.
#' @return Numeric gradient vector of length \code{ncol(X) + 1}.
#' @keywords internal
.betaregscale_grad_fixed_cpp <- function(param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_grad_fixed_cpp`, param, X, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

#' @title C++ gradient for variable-dispersion log-likelihood
#' @description Central-difference gradient for the variable-dispersion model.
#' @param param  Parameter vector.
#' @param X      Mean design matrix.
#' @param Z      Dispersion design matrix.
#' @param y_left  Left endpoints.
#' @param y_right Right endpoints.
#' @param yt     Midpoint responses.
#' @param delta  Integer censoring indicators.
#' @param link_mu_code  Integer mean link code.
#' @param link_phi_code Integer dispersion link code.
#' @param repar  Integer reparameterization type.
#' @return Numeric gradient vector.
#' @keywords internal
.betaregscale_grad_variable_cpp <- function(param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar) {
    .Call(`_betaregscale_betaregscale_grad_variable_cpp`, param, X, Z, y_left, y_right, yt, delta, link_mu_code, link_phi_code, repar)
}

